/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author isabe
 */
import Modelo.Desarrollo;
import Modelo.Estudiante;
import Modelo.Matematicas;
import Modelo.Materia;
import Modelo.Curso;

public class VistaTecnologia extends javax.swing.JFrame {

    private Curso curso;

    /**
     * Creates new form VistaTecnologia
     */
    public VistaTecnologia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombre = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        mostrarEstudiantes = new javax.swing.JButton();
        ordenarPromedio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        codigo = new javax.swing.JTextField();
        notaMatematicas = new javax.swing.JTextField();
        notaSoftware = new javax.swing.JTextField();
        notaHardware = new javax.swing.JTextField();
        notaLimite = new javax.swing.JTextField();
        crearCurso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cantidad = new javax.swing.JTextField();
        filtrar = new javax.swing.JButton();
        incrementarNota = new javax.swing.JButton();
        incremento = new javax.swing.JTextField();
        modificarNota = new javax.swing.JButton();
        comboMateria = new javax.swing.JComboBox<>();
        codigoBuscar = new javax.swing.JTextField();
        nuevaNota = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombre.setText("Nombre...");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        agregar.setBackground(new java.awt.Color(204, 204, 204));
        agregar.setText("Agregar Estudiante");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        mostrarEstudiantes.setBackground(new java.awt.Color(204, 204, 204));
        mostrarEstudiantes.setText("Mostrar estudiantes");
        mostrarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarEstudiantesActionPerformed(evt);
            }
        });

        ordenarPromedio.setBackground(new java.awt.Color(204, 204, 204));
        ordenarPromedio.setText("Ordenar de forma ascendente");
        ordenarPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarPromedioActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Resultado");
        jScrollPane1.setViewportView(jTextArea1);

        codigo.setText("Código...");
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });

        notaMatematicas.setText("Nota Matemáticas...");
        notaMatematicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaMatematicasActionPerformed(evt);
            }
        });

        notaSoftware.setText("Nota Software...");

        notaHardware.setText("Nota Hardware...");
        notaHardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaHardwareActionPerformed(evt);
            }
        });

        notaLimite.setText("Nota lim...");
        notaLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaLimiteActionPerformed(evt);
            }
        });

        crearCurso.setBackground(new java.awt.Color(204, 204, 204));
        crearCurso.setText("Crear curso");
        crearCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCursoActionPerformed(evt);
            }
        });

        jLabel1.setText("Opciones");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Sistema de Gestión de Estudiantes");

        Cantidad.setText("Cantidad est...");
        Cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadActionPerformed(evt);
            }
        });

        filtrar.setBackground(new java.awt.Color(204, 204, 204));
        filtrar.setText("Filtrar mayores a");
        filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarActionPerformed(evt);
            }
        });

        incrementarNota.setBackground(new java.awt.Color(204, 204, 204));
        incrementarNota.setText("Incrementar nota");
        incrementarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrementarNotaActionPerformed(evt);
            }
        });

        incremento.setText("Incremento");
        incremento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrementoActionPerformed(evt);
            }
        });

        modificarNota.setBackground(new java.awt.Color(204, 204, 204));
        modificarNota.setText("Modificar la nota de un estudiante");
        modificarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarNotaActionPerformed(evt);
            }
        });

        comboMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hardware", "Software", "Matemáticas" }));

        codigoBuscar.setText("Codigo del est. a buscar");

        nuevaNota.setText("Nueva Nota");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agregar)
                            .addComponent(codigoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nuevaNota)))
                .addGap(0, 31, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(notaHardware)
                    .addComponent(nombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notaMatematicas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(notaSoftware, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(incrementarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(incremento, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(crearCurso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(mostrarEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ordenarPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(notaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearCurso)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostrarEstudiantes)
                    .addComponent(notaMatematicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ordenarPromedio)
                    .addComponent(notaSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notaHardware, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(incrementarNota)
                        .addComponent(agregar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevaNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarNota)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed

        try {

            if (curso == null) {
                jTextArea1.setText("Primero debes crear el curso.");
                return;
            }

            String nom = nombre.getText();
            int cod = Integer.parseInt(codigo.getText());

            double notaMate = Double.parseDouble(notaMatematicas.getText());
            double notaSoft = Double.parseDouble(notaSoftware.getText());
            double notaHard = Double.parseDouble(notaHardware.getText());

            Materia matematicas = new Matematicas(notaMate);
            Materia desarrollo = new Desarrollo(notaSoft, notaHard);

            Estudiante estudiante = new Estudiante(nom, cod, matematicas, desarrollo);

            String mensaje = curso.agregarEstudiante(estudiante);

            jTextArea1.setText(mensaje);

        } catch (Exception e) {
            jTextArea1.setText("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void notaHardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaHardwareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaHardwareActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void notaMatematicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaMatematicasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaMatematicasActionPerformed

    private void crearCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCursoActionPerformed
        // TODO add your handling code here:  
        try {
            int cantidad = Integer.parseInt(Cantidad.getText());

            curso = new Curso(cantidad);

            jTextArea1.setText("Curso creado para " + cantidad + " estudiantes.");

        } catch (Exception e) {
            jTextArea1.setText("Error: " + e.getMessage());
        }

    }//GEN-LAST:event_crearCursoActionPerformed

    private void mostrarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarEstudiantesActionPerformed
        // TODO add your handling code here:
        if (curso == null) {
            jTextArea1.setText("Primero debes crear el curso.");
            return;
        }

        jTextArea1.setText(curso.mostrarEstudiantes());
    }//GEN-LAST:event_mostrarEstudiantesActionPerformed

    private void CantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadActionPerformed

    private void ordenarPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarPromedioActionPerformed
        // TODO add your handling code here:
        if (curso == null) {
            jTextArea1.setText("Primero debes crear el curso.");
            return;
        }
        curso.ordenarAscendente();

        jTextArea1.setText("Estudiantes ordenados por definitiva:\n\n"
                + curso.mostrarEstudiantes());
    }//GEN-LAST:event_ordenarPromedioActionPerformed

    private void notaLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaLimiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaLimiteActionPerformed

    private void filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarActionPerformed
        // TODO add your handling code here:
        try {
            if (curso == null) {
                jTextArea1.setText("Primero debes crear el curso.");
                return;
            }

            double notaLim = Double.parseDouble(notaLimite.getText());

            jTextArea1.setText(curso.listaMayorA(notaLim));

        } catch (Exception e) {
            jTextArea1.setText("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_filtrarActionPerformed

    private void incrementarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrementarNotaActionPerformed
        // TODO add your handling code here:
        try {
            if (curso == null) {
                jTextArea1.setText("Primero debes crear el curso.");
                return;
            }

            double aumentar = Double.parseDouble(incremento.getText());

            curso.incrementoNotas(aumentar);

            jTextArea1.setText("Notas actualizadas:\n\n" + curso.mostrarEstudiantes());

        } catch (Exception e) {
            jTextArea1.setText("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_incrementarNotaActionPerformed

    private void incrementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incrementoActionPerformed

    private void modificarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarNotaActionPerformed
        // TODO add your handling code here:
        try {
            if (curso == null) {
                jTextArea1.setText("Primero debes crear el curso.");
                return;
            }

            int cod = Integer.parseInt(codigoBuscar.getText());
            double nuevaNot = Double.parseDouble(nuevaNota.getText());

            Estudiante estudiante = curso.buscarEstudiante(cod);

            if (estudiante == null) {
                jTextArea1.setText("Estudiante no encontrado.");
                return;
            }

            String opcion = comboMateria.getSelectedItem().toString();

            if (opcion.equals("Hardware")) {
                Desarrollo desa = (Desarrollo) estudiante.getDesarrollo();
                desa.modificarNota(1, nuevaNot);

            } else if (opcion.equals("Software")) {
                Desarrollo desa = (Desarrollo) estudiante.getDesarrollo();
                desa.modificarNota(2, nuevaNot);

            } else if (opcion.equals("Matemáticas")) {
                estudiante.getMatematicas().setNota(nuevaNot);
            }

            jTextArea1.setText("Nota modificada correctamente.\n\n");

        } catch (Exception e) {
            jTextArea1.setText("Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_modificarNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTecnologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTecnologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTecnologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTecnologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTecnologia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cantidad;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField codigoBuscar;
    private javax.swing.JComboBox<String> comboMateria;
    private javax.swing.JButton crearCurso;
    private javax.swing.JButton filtrar;
    private javax.swing.JButton incrementarNota;
    private javax.swing.JTextField incremento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton modificarNota;
    private javax.swing.JButton mostrarEstudiantes;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField notaHardware;
    private javax.swing.JTextField notaLimite;
    private javax.swing.JTextField notaMatematicas;
    private javax.swing.JTextField notaSoftware;
    private javax.swing.JTextField nuevaNota;
    private javax.swing.JButton ordenarPromedio;
    // End of variables declaration//GEN-END:variables
}
